# fly.toml app configuration file generated for inventoryapp2301 on 2023-10-23T19:31:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inventoryapp2301"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
